[tool.poetry]
name = "pubfeed"
version = "0.1.0"
description = ""
authors = ["Tito Malone"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
